### ISSUE TITLE
UnicodeEncodeError in avocado check

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/avocado#282]
If the name of an unknown field or model contains utf-8 characters in the model, I get a `UnicodeEncodeError: 'ascii' codec can't encode character` exception when I run `bin/manage.py avocado check`.  When I use the following `__str__` definition for DataField, the problem goes away:

    def __str__(self):
        return unicode(self).encode('utf-8')

Stack trace:

    (pcgc-dev2-env)6003088c56d0:pcgc murphyke$ bin/manage.py avocado check
    Traceback (most recent call last):
      File "bin/manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
        utility.execute()
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/avocado/management/commands/avocado.py", line 65, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
        output = self.handle(*args, **options)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/avocado/management/commands/avocado.py", line 85, in handle
        return klass.execute(*args, **defaults)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
        output = self.handle(*args, **options)
      File "/Users/murphyke/Documents/code/python/pcgc-dev2-env/lib/python2.7/site-packages/avocado/management/subcommands/check.py", line 61, in handle
        print template.render(Context(context))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2103' in position 414: ordinal not in range(128)

**Comment by bruth** [comment]
Huh. I wrote a test that creates an unknown data field so the check command outputs it (which is what the `template.render(..)` call is doing) and it works for me.

![screen shot 2015-01-13 at 9 05 19 pm](https://cloud.githubusercontent.com/assets/515142/5732886/f774b7de-9b67-11e4-998b-59ea9db3d2fe.png)

Can you identity the contents of the field that is failing so I can try to reproduce the case exactly?

**Comment by murphyke** [comment]
This was failing because my terminal's LC_CTYPE was US-ASCII.  When I switched LC_CTYPE to en_US.UTF-8, sys.stdout.encoding becomes UTF-8, and it works fine.

**Comment by bruth** [comment]
Oye. When you did your above *fix* of adding `__str__`, what did the UTF-8 encoded character appear as? A block? It may still be good to add the `__str__` method so this does not happen to others.
